name: chapasdk
description: Chapa flutter library to accept payment via Card, Bank or telebirr etc.
version: 0.0.3
homepage: https://github.com/chapa-et/chapa-flutter

environment:
  sdk: ">=2.15.0<3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.0
  flutter_inappwebview: ^5.4.3+7
  connectivity_plus: ^2.3.6+1
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
